name: Fetch Proxy Data

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜执行

jobs:
  fetch-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # 使用 Node.js 20 版本

      - name: Install dependencies
        run: npm install

      - name: Run main.ts
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # 使用 GitHub Secrets
        run: node --loader ts-node/esm main.ts  # 使用 ts-node 运行 TypeScript 文件