name: Fetch Proxy Data

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜执行
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  fetch-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # 使用 Node.js 20 版本

      - name: Install dependencies
        run: npm install

      - name: Run main.ts
        run: |
          node --loader ts-node/esm main.ts  # 使用 ts-node 运行 TypeScript 文件
          mv proxy.json new_proxy.json

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure target branch exists
        run: |
          git fetch origin proxy || true
          git checkout -b proxy origin/proxy || git checkout proxy
          git pull origin proxy --rebase

      - name: Commit and push changes
        run: |
          rm proxy.json
          mv new_proxy.json proxy.json
          git add proxy.json
          if git diff --quiet proxy.json; then
            echo "No changes in proxy.json. Skipping commit and push."
          else
            # 设置提交信息
            commit_message="proxy update $(date '+%Y-%m-%d')"
            git add proxy.json
            git commit -m "$commit_message"
            git push origin proxy
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # 使用 GitHub Secrets

permissions:
  contents: write  # 允许写入内容
